### PR TITLE
Allow the plugin to be updates via GitHub Updater

### PR DESCRIPTION
**Pull request by grappler**
Sorry, something went wrong in the other PR.
Add support for https://github.com/afragen/github-updater

### CODE REVIEW

**Comment by swissspidy** [comment]
Hey @grappler,

Thanks for your pull requests! In the current form of this plugin, these totally make sense.

However, in the future the plugin's structure will be more similar to the one of [WP Widget Disable](https://github.com/wearerequired/WP-Widget-Disable) (using [grunt-wp-plugin](https://github.com/wearerequired/grunt-wp-plugin/)), where the GitHub repo includes all the dev files, and we build a WordPress.org-ready zip file using `grunt release`.

I think this would only work well with the GitHub Updater when we add custom releases on GitHub as well, and this is currently not supported (see afragen/github-updater/issues/224).

I guess in this scenario wearerequired/simple-user-adding/pull/14 would be unneeded?

---

Let me know if everything's clear. I can update the plugin's structure this afternoon if you want, so you can get a better picture.

**Comment by afragen** [comment]
@swissspidy the issue referenced above on GitHub Updater is primarily one of how GitHub deals with remote repos. As long as you actually include remote repos and not just reference them everything should be fine. Updating should work regardless except under these circumstances.

Let me know if there are further questions?

**Comment by swissspidy** [comment]
The thing is, in my plugin I currently generate some files only on _build_, like all minified files and the `readme.txt`. These will only be available on WordPress.org (where the GitHub Updater wouldn't be needed) or when I add the final build as a release asset on GitHub. @afragen Would the latter work with the GitHub Updater plugin? I mentioned this issue because I thought it'd solve the same problem.

**Comment by afragen** [comment]
How do you create a release asset on GitHub? I'm still trying to understand the concept.

If GitHub provides an endpoint to a usable zipball then the answer is it should work.

**Comment by swissspidy** [comment]
1. Head over to your repo. Just under the description, click `x releases`.
2. Add a new release.
3. Attach a new binary to that release.

This binary is what should be downloaded.

**Comment by afragen** [comment]
This is now supported in GitHub Updater.

**Comment by grappler** [comment]
Thanks @afragen I suppose it not needed anymore now the plugin is on w.org. https://wordpress.org/plugins/simple-user-adding/

**Comment by swissspidy** [comment]
Yeah, but still useful for other plugins in the works. Thank you! :)

—
Pascal

**Pull request closed without merging**
